version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306" # HOST:CONTAINER
    environment:
      MYSQL_DATABASE: diarydb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      #      - D:/mysql/data:/var/lib/mysql
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data: