spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/diarydb?serverTimezone=Asia/Seoul
      username: root
      password: admin

my:
  value: 100